# Name of workflow
name: main-CI

on:
  push: 
    branches: 
      - master
  pull_request:
    branches: 
      - master


jobs:
  build:    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    
    steps:
        # Checks-out your repository under
      - name: Git clone my repo
      - uses: actions/checkout@v2
  
      - name: npm install, build
        # Install and build project
        run: |
          make install
      - name: Run linter
        # Run Linter
        run: |
          make lint
        

